# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Defines that a commit to the master branch should trigger this build
trigger:
- master


# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin


pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  version: '1.5.0'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'src/*.sln'
  enabled: true
- task: MSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: "src/*.sln"
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/t:restore;build /p:PackageVersion=$(version) /p:PackageOutputPath=$(build.SourcesDirectory)\public /p:AssemblyFileVersion=$(version) '
    clean: false
  enabled: true
- task: XamarinAndroid@1
  inputs:
    projectFile: 'src/Plugin.FileUploader.Android/*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/t:restore;build /p:PackageVersion=$(version) /p:PackageOutputPath=$(build.SourcesDirectory)\public /p:AssemblyFileVersion=$(version) '
  enabled: false

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'src/*.sln'
    nobuild: true
    versioningScheme: 'off'
  enabled: false

# The last task is a nuget command, nuget push
# This will push any .nupkg files to the 'PackagesFeed' artifact feed
# allowPackageConflicts allows us to build the same version and not throw an error when trying to push
# instead it just ingores the latest package unless the version changes
- task: CopyFiles@2
  displayName: 'Copy APK to Staging Directory'
  inputs:
       sourceFolder: $(build.SourcesDirectory) 
       contents: |
         **/*.nupkg
       targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: '$(version)'
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    publishLocation: Container
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactstagingdirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'
  enabled: false
- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(build.artifactstagingdirectory)/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishVstsFeed: 'PackagesFeed2'
    versioningScheme: 'off'
    allowPackageConflicts: true
